app_url=https://nikita-filonov.github.io/qa-automation-engineer-ui-course
headless=True
browsers=[chromium]
test_user={'email': 'user.name@gmail.com', 'username': 'username', 'password': 'password'}
test_data={'image_png_file': 'testdata/files/image.png'}
videos_dir=videos
tracing_dir=tracing
allure_results_dir=allure-results
browser_state_file=browser-state.json
ui_coverage_apps=[
    {
        "key": "ui-course",
        "url": "https://nikita-filonov.github.io/qa-automation-engineer-ui-course/#/auth/login",
        "name": "UI Course",
        "tags": ["UI", "COURSES"],
        "repository": "https://github.com/Nikita-Filonov/qa-automation-engineer-ui-course"
    }
]